version: '3.4'
services:
  user-management:
    image: user-management:development
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "8080:8080"
      - "8082:8082"
      - "8888:8888"
    volumes:
      - ./application.log:/home/gradle/application.log
