application:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link'
    allow-credentials: true
    max-age: 1800
  security:
    base64-secret: fqps8tNGuyy3Rwi3KuieWws5Luj7Jp7naZaTmN0HvtNJ2ZWudUnVhCDy3YOqrne+UHhceYY6jyjbnDei05efVA4NVOFv2oUZhsd8S63IdcgtWCFPqY86/ouFmCy40OcA9WkyOx0A8tuPKayJELhQURfzHUkvOjTaWYgydKWzoHw=
    token-validity-in-seconds: 86400

log:
  file: ./application.log

logging:
  level:
    ROOT: INFO
    com.sbakic.usermanagement: DEBUG

server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./build/h2/db/user_management;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
    tcp:
      port: 8082
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
